kind: PersistentVolume
apiVersion: v1
metadata:
  name: kyungwon-db-vol
  labels:
    type: local
spec:
  storageClassName: hdd
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyungwon-db-vol
spec:
  storageClassName: hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kyungwon-moodle-vol
  labels:
    type: local
spec:
  storageClassName: hee
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyungwon-moodle-vol
spec:
  storageClassName: hee
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi