apiVersion: v1
kind: Service
metadata:
  name: kyungwon-db
  labels:
    app: moodle
spec:
  ports:
    - port: 3306
  selector:
    app: moodle
  clusterIP: None
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyungwon-db
  labels:
    app: moodle
spec:
  selector:
    matchLabels:
      app: moodle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - image: bitnami/mariadb:latest
        name: kyungwon-mariadb
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_PASSWORD
          value : "bitnami"
        - name: MARIADB_USER
          value : "bn_moodle"
        - name: MARIADB_DATABASE
          value: "bitnami_moodle"
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mariadb-data
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: kyungwon-db-vol