apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyungwon-moodle
  labels:
    app: moodle
spec:
  selector:
    matchLabels:
      app: moodle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - image: bitnami/moodle:latest
        name: kyungwon-moodle
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MOODLE_DATABASE_PASSWORD
          value : "bitnami"
        - name: MOODLE_DATABASE_USER
          value : "bn_moodle"
        - name: MOODLE_DATABASE_NAME
          value: "bitnami_moodle"
        - name: MARIADB_HOST
          value: "kyungwon-db"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/bitnami/moodle"
          name: moodle-data
      volumes:
      - name: moodle-data
        persistentVolumeClaim:
          claimName: kyungwon-moodle-vol
---
apiVersion: v1
kind: Service
metadata:
  name: kyungwon-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer