# lb을 할당하기 위함 moodle과 연결할 것
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 211.183.3.201-211.183.3.211
      - 211.183.3.231-211.183.3.239