apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymoodle
  labels:
    app: moodle
spec:
  selector:
    matchLabels:
      app: moodle
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
        tier: frontend
    spec:
      containers:
      - image: bitnami/moodle:latest
        name: mymoodle
        env:
        - name: MOODLE_DATABASE_USER
          value: moodledb.c492xbmtirc0.ap-northeast-1.rds.amazonaws.com:3306
        - name: MOODLE_DATABASE_NAME
          value: "root"
        - name: MOODLE_DATABASE_PASSWORD
          value : test12345
        - name: MYSQL_HOST
          value: moodledb
    