apiVersion: v1
kind: Service
metadata:
  name: lb
  namespace: mysql
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
